# Tutorial

`finance` 패키지의 `naver`, `krx` 모듈의 함수는 호출 시점에 __네이버__ 또는 __KRX__ 로부터 데이터를 크롤링하여 정보를 제공합니다. 그렇기 때문에 `finance` 패키지의 함수를 동시에 여러번 호출하지 마세요. 해당 함수가 크롤링하는 __네이버__ 또는 __KRX__ 로부터 블락 당할 수 있습니다. 여러번의 함수 호출이 필요할 때는`time.sleep(second)`를 이용하여 함수 사이에  interval을 두세요.

- [NAVER](#NAVER)
- [KRX](#KRX)

## NAVER

In [1]:
import finance.naver as naver

In [2]:
naver.get_fundamentals()

,N,종목명,현재가,전일비,등락률,액면가,거래량,거래대금,전일거래량,시가,...,보통주배당금,매출액증가율,영업이익증가율,외국인비율,PER,ROE,ROA,PBR,유보율,토론실
1,1.0,삼성전자,46950.0,4450.0,+10.47%,100.0,49489302.0,2240124.0,41701626.0,43850.0,...,1416.0,-5.49,-52.84,55.24,14.83,8.69,6.28,1.25,28856.0,NaN
2,2.0,SK하이닉스,78700.0,9300.0,+13.40%,5000.0,7209904.0,546025.0,8192363.0,73000.0,...,1000.0,-33.27,-86.99,49.18,28.46,4.25,3.14,1.12,1287.0,NaN
3,3.0,삼성전자우,39150.0,3150.0,+8.75%,100.0,4131151.0,157206.0,3367606.0,36900.0,...,NaN,NaN,NaN,89.22,12.37,NaN,NaN,1.04,NaN,NaN
4,4.0,삼성바이오로직스,476000.0,40000.0,+9.17%,2500.0,505987.0,238212.0,589740.0,452500.0,...,NaN,30.94,64.77,10.74,155.20,4.77,3.41,7.23,2539.1,NaN
5,5.0,NAVER,156000.0,13000.0,+9.09%,100.0,959852.0,147079.0,1033851.0,151500.0,...,376.0,18.02,-24.66,57.92,44.09,10.56,3.58,3.91,44216.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,1558.0,ARIRANG KRX300자유소비재,7150.0,480.0,+7.20%,0.0,54.0,0.0,53.0,6870.0,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN
12,1559.0,KODEX 운송,2015.0,100.0,-4.73%,0.0,27800.0,60.0,30662.0,2140.0,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN
13,1560.0,KBSTAR 지주회사,4875.0,305.0,+6.67%,0.0,729.0,3.0,31.0,4665.0,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN
17,1561.0,ARIRANG 스마트베타 Momentum,5635.0,340.0,+6.42%,0.0,4850.0,26.0,83.0,5440.0,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN
18,1562.0,KBSTAR 일본TOPIX레버리지(H),9640.0,540.0,+5.93%,0.0,971.0,9.0,478.0,9260.0,...,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
naver.get_performances_by_sector()

,업종명,전일대비,전일대비 등락현황 전체,전일대비 등락현황 상승,전일대비 등락현황 보합,전일대비 등락현황 하락,등락그래프
0,출판,+16.16%,5.0,4.0,1.0,0.0,100%
1,복합기업,+14.74%,16.0,15.0,0.0,1.0,91%
2,전자장비와기기,+13.07%,81.0,74.0,6.0,1.0,80%
3,전기제품,+12.34%,40.0,39.0,1.0,0.0,76%
4,증권,+12.13%,35.0,33.0,1.0,1.0,75%
...,...,...,...,...,...,...,...
121,종이와목재,+3.10%,16.0,14.0,0.0,2.0,19%
122,판매업체,+2.14%,9.0,5.0,2.0,2.0,13%
123,항공사,-10.01%,11.0,10.0,0.0,1.0,61%
124,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
sector_companies_dict = naver.get_companies_by_sector()

# * means kosdaq 
print("소프트웨어 관련 기업")
print(sector_companies_dict['소프트웨어'])

100%|██████████| 79/79 [01:32<00:00,  1.17s/it]

소프트웨어 관련 기업
['코닉글로리 *', '더존비즈온', '디지캡 *', '키네마스터 *', '에스에스알 *', '지니언스 *', '미디어젠 *', '시큐브 *', '링크제니시스 *', '케이사인 *', '드림시큐리티 *', '안랩 *', '서호전기 *', '아톤 *', '윈스 *', '엑셈 *', '인프라웨어 *', '웹케시 *', '휴네시온 *', '파수닷컴 *', '퓨전 *', '비즈니스온 *', '알서포트 *', '네이블 *', '포시에스 *', '한글과컴퓨터 *', '텔코웨어', '누리텔레콤 *', 'SGA솔루션즈 *', '라온시큐어 *', '한컴MDS *', '포비스티앤씨 *', '이니텍 *', '소프트캠프 *', '다우데이타 *', '한류AI센터 *', '알티캐스트 *', '모바일리더 *', '플랜티넷 *', '투비소프트 *', 'SGA *', '한컴위드 *', '지란지교시큐리티 *', '이글루시큐리티 *', '이스트소프트 *', '엔지스테크널러지 *', '셀바스AI *', '오상자이엘 *', '핸디소프트 *']

## KRX

In [5]:
import finance.krx as krx

In [6]:
krx.get_fundamentals(2020, 3, 24)

,일자,종목코드,종목명,관리여부,종가,EPS,PER,BPS,PBR,주당배당금,배당수익률,게시물 일련번호,총카운트
0,2020/03/24,000250,삼천당제약,-,"27,950",409,68.34,"6,719",4.16,50,0.18,1,2331.0
1,2020/03/24,000440,중앙에너비스,-,"5,200",958,5.43,"7,269",0.72,160,3.08,2,NaN
2,2020/03/24,001000,신라섬유,-,"1,040",7,148.57,587,1.77,0,0.00,3,NaN
3,2020/03/24,001540,안국약품,-,"7,400","1,154",6.41,"11,253",0.66,220,2.97,4,NaN
4,2020/03/24,001810,무림SP,-,"1,295",505,2.56,"9,212",0.14,35,2.70,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2285,2020/03/24,33626L,두산퓨얼셀2우B,-,"6,200",-,-,-,-,NaN,NaN,2286,NaN
2286,2020/03/24,336370,두산솔루스,-,"16,750",-,-,-,-,NaN,NaN,2287,NaN
2287,2020/03/24,33637K,두산솔루스1우,-,"7,020",-,-,-,-,NaN,NaN,2288,NaN
2288,2020/03/24,33637L,두산솔루스2우B,-,"17,000",-,-,-,-,NaN,NaN,2289,NaN
2289,2020/03/24,344820,케이씨씨글라스,-,"13,200",-,-,-,-,NaN,NaN,2290,NaN

In [7]:
krx.get_fundamentals_from_to(2020, 3, 17,
                             2020, 3, 19)

3it [00:13,  4.36s/it]

,일자,종목코드,종목명,관리여부,종가,EPS,PER,BPS,PBR,주당배당금,배당수익률,게시물 일련번호,총카운트
0,2020/03/17,053950,경남제약,-,"5,650",327,17.28,"2,351",2.4,0,0.00,1,2331.0
1,2020/03/17,066790,씨씨에스,관리종목,423,-,-,285,1.48,0,0.00,2,NaN
2,2020/03/17,109610,에스와이,-,"3,560",60,59.33,"4,478",0.79,0,0.00,3,NaN
3,2020/03/17,225330,씨엠에스에듀,-,"4,050",282,14.36,"2,196",1.84,260,6.42,4,NaN
4,2020/03/17,311390,네오크레마,-,"4,705",895,5.26,"4,090",1.15,0,0.00,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2285,2020/03/19,118000,우리들휴브레인,-,"1,530",-,-,757,2.02,0,0.00,2286,NaN
2286,2020/03/19,004720,우리들제약,-,"4,480",390,11.49,"4,904",0.91,0,0.00,2287,NaN
2287,2020/03/19,001529,동양3우B,-,"20,000",-,-,-,-,150,0.75,2288,NaN
2288,2020/03/19,005090,삼광글라스,-,"27,900",-,-,"57,464",0.49,750,2.69,2289,NaN
2289,2020/03/19,090355,노루페인트우,-,"8,130",-,-,-,-,255,3.14,2290,NaN